Add "Fields" and "Level" to LogEntry
Ideine/LogsSender pull request #13
Opened 2023-11-17 16:18 UTC by Meltical

2023-11-17 16:43 UTC, VJubert requested changes

2023-11-17 16:43 UTC, VJubert commented on Internals/LogService.cs
> +			string fields = ((IObjectWriter) new JsonLogWriter()).WriteObject("Fields", fillLogEntry).ToString();
@Meltical pourquoi tu réécrits content dans un autre champ, pourquoi tu ajoutes level alors que c'est déjà dans content ? (et pourquoi tu fais ça sur la version mobile du paquet)

2023-11-17 19:13 UTC, Meltical commented on Internals/LogService.cs
> +			string fields = ((IObjectWriter) new JsonLogWriter()).WriteObject("Fields", fillLogEntry).ToString();
@VJubert Je te montre Lundi ;)

2023-11-20 10:34 UTC, closed without merging

2023-11-20 10:35 UTC, Meltical commented
Cf: 0.2.8